Add a new error message for Dump Offload
ibm-openbmc/phosphor-logging pull request #81
Opened 2024-12-02 09:59 UTC by SwethaParasa

We log the same error for Dump Delete and Offload right now. Adding a new error to distinguish between a dump delete and a dump offload.

Change-Id: I19282b3e7971702b6b3756aaf060ceeb200d2f94

2024-12-02 12:51 UTC, devenrao approved these changes

2024-12-02 15:30 UTC, geissonator commented
add to approvelist

2024-12-02 15:51 UTC, spinler commented
Can this go upstream?

2024-12-03 05:22 UTC, SwethaParasa commented
> Can this go upstream?

yes, will push upstream patch.

2024-12-04 13:58 UTC, spinler requested changes
Can you update the commit message like you did upstream?

2024-12-04 13:59 UTC, SwethaParasa commented
> Can you update the commit message like you did upstream?

sure

2024-12-04 14:03 UTC, SwethaParasa commented
> Can you update the commit message like you did upstream?

Done

2024-12-04 14:12 UTC, spinler approved these changes

2024-12-16 14:28 UTC, merged